name: Bug report
description: Report a defect or unexpected behavior
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide minimal steps or a small example.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: weevr version
      placeholder: "0.1.0"
    validations:
      required: false

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.11.x"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant output (sanitized).
      render: shell
    validations:
      required: false
